### ISSUE TITLE
Set Scaling of window

### ISSUE THREAD

**Issue by jason990420** [jason990420/PySimpleGUI-Solution#80]
![image](https://user-images.githubusercontent.com/55352169/122561675-b8ca9500-d074-11eb-9ee2-c5849e85b117.png)

Set `scaling` of window

``` python
import PySimpleGUI as sg

def new_window(win, scale=None):
    if win:
        if scale is not None:
            win.TKroot.tk.call('tk', 'scaling', scale)
        win.close()
    layout = [
        [sg.Text("Text Line here"), sg.Button("POPUP")],
        [sg.Button(item) for item in buttons],
    ]
    return sg.Window('Title', layout, finalize=True)

sg.theme("DarkBlue3")
sg.set_options(font=("Courier New", 16))

buttons = ("DOWN", "NORMAL", "UP")
window = new_window(None, None)
dpi = window.TKroot.winfo_fpixels('1i')
now = dpi/72
scales = [now/2, now, now*2]

while True:
    event, values = window.read()
    if event == sg.WINDOW_CLOSED:
        break
    elif event in buttons:
        scale = scales[buttons.index(event)]
        window = new_window(window, scale)
    elif event == 'POPUP':
        sg.popup_ok("Hello World !")

window.close()
```

**Comment by PySimpleGUI** [comment]
What do you think is the best way to provide this capability in the PySimpleGUI APIs? 

Should it be at the Window level or is it a system-wide setting that should be applied to all windows?

I **_think_** it's likely system-wide which would enable it to work on windows that the user doesn't create like popups.

It could be both a system setting (the default) and a parameter used when a Window is created.  I'm a little unclear on the best term and type to use.  Does a fraction of "now" make sense so that it's a float with a value of .5, 1, 2 as in your example?

```python
window = sg.Window(title, layout, scale=0.5)
```

and an option of `window_scaling` that defaults to 1.0.

```python
sg.set_options(window_scaling=2.0)
```

**Comment by jason990420** [comment]
> tk scaling ?-displayof window? ?number?
> 
> Sets and queries the current scaling factor used by Tk to convert between physical units (for example, points, inches, or millimeters) and pixels. The number argument is a floating point number that specifies the number of pixels per point on window's display. If the window argument is omitted, it defaults to the main window. If the number argument is omitted, the current value of the scaling factor is returned.
> 
> A “point” is a unit of measurement equal to 1/72 inch. A scaling factor of 1.0 corresponds to 1 pixel per point, which is equivalent to a standard 72 dpi monitor. A scaling factor of 1.25 would mean 1.25 pixels per point, which is the setting for a 90 dpi monitor; setting the scaling factor to 1.25 on a 72 dpi monitor would cause everything in the application to be displayed 1.25 times as large as normal. The initial value for the scaling factor is set when the application starts, based on properties of the installed monitor, but it can be changed at any time. Measurements made after the scaling factor is changed will use the new scaling factor, but it is undefined whether existing widgets will resize themselves dynamically to accommodate the new scaling factor.

1.0 for 72 DPI, but not default setting of tkinter. It is default `96.09458128078816` for DPI, not 72, so scale is `1.334646962233169`  when run tkinter on my notebook.

It can be called with window (name) argument, but I am not sure how to call it and what condition it will work and for what window.

**Comment by PySimpleGUI** [comment]
While playing with the code, I noticed that all windows must be closed in order for the scaling code to work correctly.  If the non-blocking popup window is open, then the other window never changes size.

```python
import PySimpleGUI as sg

def make_win():
    layout = [  [sg.Text('My Window')],
                [sg.Input(key='-IN-')],
                [sg.Text(size=(12,1), key='-OUT-')],
                [sg.Button('Go'), sg.Button('Exit')]  ]

    window = sg.Window('Window Title', layout)
    return window

def do_scale():
    window = sg.Window('test', [[sg.T('')]], alpha_channel=0, finalize=True)
    root = window.TKroot
    dpi = root.winfo_fpixels('1i')
    now = dpi / 72
    scale = now * 2
    root.tk.call('tk', 'scaling', scale)
    window.close()


def main():
    # sg.popup_non_blocking('popup')
    do_scale()
    window = make_win()
    while True:             # Event Loop
        event, values = window.read()
        print(event, values)
        if event == sg.WIN_CLOSED or event == 'Exit':
            break
        if event == 'Go':
            do_scale()
            window.close()
            window = make_win()
    window.close()

if __name__ == '__main__':
    main()
```

**Comment by jason990420** [comment]
New option `scaling` added in `Window`, so update example as following.
You can find the unit of size I used when reconfigure Graph in example code is 'p', not integer, or it will be in pixels.

> Various lengths, widths, and other dimensions of widgets can be described in many different units.
> • If you set a dimension to an integer, it is assumed to be in pixels.
> • You can specify units by setting a dimension to a string containing a number followed by:
> Table 3. Dimensional units
> | string | dimension |
> | --- | --- |
> | c | Centimeters |
> | i | Inches |
> | m | Millimeters |
> | p | Printer's points (about 1/72″) |

``` python
import PySimpleGUI as sg

def new_window(win, scale=None):
    layout = [
        [sg.Text("Text Line here"), sg.Button("POPUP")],
        [sg.Canvas(size=(110, 110), background_color='blue', key='GRAPH')],
        [sg.Button(item) for item in ("DOWN", "NORMAL", "UP")],
    ]
    window = sg.Window('Title', layout, finalize=True, scaling=scale)
    window['GRAPH'].Widget.configure(width='110p', height='110p')
    window['GRAPH'].Widget.create_oval('5p', '5p', '105p', '105p', fill='green', outline='white', width='5p')
    return window

sg.theme("DarkBlue3")
sg.set_options(font=("Courier New", 16))

window = new_window(None, None)
dpi = window.TKroot.winfo_fpixels('1i')
now = dpi/72
scales = {"DOWN":now/2, "NORMAL":now, "UP":now*2}

while True:
    event, values = window.read()
    if event == sg.WINDOW_CLOSED:
        break
    elif event in scales:
        scale = scales[event]
        window.close()
        window = new_window(window, scale)
    elif event == 'POPUP':
        sg.popup_ok("Hello World !")

window.close()
```
